name: Tetris
description: "A Tetris game, like all of the tetris games but in flutter."
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.3
  audioplayers: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/img/logo.png
  fonts:
    - family: Bitcount
      fonts:
        - asset: assets/font/Bitcount-VF.ttf
flutter_icons:
  android: true
  image_path: assets/img/logo.png
